repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=10000']  # Prevent files >10MB
      - id: detect-private-key

  # Python linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # # Jupyter notebook handling
  # - repo: https://github.com/nbQA-dev/nbQA
  #   rev: 1.7.1
  #   hooks:
  #     - id: nbqa-ruff
  #       args: [--fix, --ignore=E402,F401]  # Allow imports anywhere, unused imports
  #     - id: nbqa-isort
  #       additional_dependencies: [isort]

  # # Clear notebook outputs (crucial for ML)
  # - repo: https://github.com/kynan/nbstripout
  #   rev: 0.6.1
  #   hooks:
  #     - id: nbstripout
  #       args: ['--keep-output', '--keep-count']  # Keep cell execution numbers

  # # Security scanning
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.5
  #   hooks:
  #     - id: bandit
  #       args: [-c, pyproject.toml]
  #       additional_dependencies: ["bandit[toml]"]

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --show-error-codes]

  # Documentation
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: [--convention=numpy]  # Or google, sphinx

  # # YAML/Config validation
  # - repo: https://github.com/adrienverge/yamllint
  #   rev: v1.35.1
  #   hooks:
  #     - id: yamllint
  #       args: [-d, relaxed]

  # # Git commit message formatting
  # - repo: https://github.com/compilerla/conventional-pre-commit
  #   rev: v3.0.0
  #   hooks:
  #     - id: conventional-pre-commit
  #       stages: [commit-msg]

  # # Dependency security check
  # - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  #   rev: v1.3.2
  #   hooks:
  #     - id: python-safety-dependencies-check

  # ML-specific: Check for secrets in config files
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json
