# # Catastrophic forgetting: grpo on countdown
# # accelerate launch --num_processes 8 --config_file config/deepspeed_zero3.yaml src/nll_to_po/llm/grpo_llm.py --model-name HuggingFaceTB/SmolLM2-360M-Instruct --n-steps 1000 --per_device_train_batch_size 1 --gradient_accumulation_steps 8 --seed $RANDOM
# # Catastrophic forgetting: grpo vs sft 
# # # 1
# # accelerate launch --num_processes 8 --config_file config/deepspeed_zero3.yaml src/nll_to_po/medical/grpo_llm.py --model-name HuggingFaceTB/SmolLM2-360M-Instruct --embed --reward-embedding-model NeuML/pubmedbert-base-embeddings-8M --n-steps 400 --per_device_train_batch_size 1 --gradient_accumulation_steps 8 --adapter-path "logs/SmolLM2-360M-Instruct/Countdown-Task-GOLD/[embeddinggemma-300m][Id][cls][0.001][peft_8][s:1000][v14]trl-grpo-20260423-110853" --seed $RANDOM
# accelerate launch --num_processes 8 --config_file config/deepspeed_zero3.yaml src/nll_to_po/medical/sft_llm.py --model-name HuggingFaceTB/SmolLM2-360M-Instruct  --max-steps 400 --per_device_train_batch_size 1 --gradient_accumulation_steps 8 --adapter-path "logs/SmolLM2-360M-Instruct/Countdown-Task-GOLD/[embeddinggemma-300m][Id][cls][0.001][peft_8][s:1000][v14]trl-grpo-20260423-110853" --seed $RANDOM
# # # 2
# accelerate launch --num_processes 8 --config_file config/deepspeed_zero3.yaml src/nll_to_po/medical/grpo_llm.py --model-name HuggingFaceTB/SmolLM2-360M-Instruct --embed --reward-embedding-model NeuML/pubmedbert-base-embeddings-8M --n-steps 400 --per_device_train_batch_size 1 --gradient_accumulation_steps 8 --adapter-path "logs/SmolLM2-360M-Instruct/Countdown-Task-GOLD/[embeddinggemma-300m][Id][cls][0.001][peft_8][s:1000][v14]trl-grpo-20260423-203840" --seed $RANDOM
# accelerate launch --num_processes 8 --config_file config/deepspeed_zero3.yaml src/nll_to_po/medical/sft_llm.py --model-name HuggingFaceTB/SmolLM2-360M-Instruct  --max-steps 400 --per_device_train_batch_size 1 --gradient_accumulation_steps 8 --adapter-path "logs/SmolLM2-360M-Instruct/Countdown-Task-GOLD/[embeddinggemma-300m][Id][cls][0.001][peft_8][s:1000][v14]trl-grpo-20260423-203840" --seed $RANDOM

# LLM finetuning: PubMedQA exps
# # SmolLM2-360M
# # # # embed Id
# accelerate launch --num_processes 8 --config_file config/deepspeed_zero3.yaml src/nll_to_po/medical/grpo_llm.py --model-name HuggingFaceTB/SmolLM2-360M-Instruct --reward-embedding-model NeuML/pubmedbert-base-embeddings-8M --n-steps 400 --per_device_train_batch_size 1 --gradient_accumulation_steps 8 --seed $RANDOM --embed
# accelerate launch --num_processes 8 --config_file config/deepspeed_zero3.yaml src/nll_to_po/medical/grpo_llm.py --model-name HuggingFaceTB/SmolLM2-360M-Instruct --reward-embedding-model NeuML/pubmedbert-base-embeddings-8M --n-steps 400 --per_device_train_batch_size 1 --gradient_accumulation_steps 8 --seed $RANDOM --embed
# accelerate launch --num_processes 8 --config_file config/deepspeed_zero3.yaml src/nll_to_po/medical/grpo_llm.py --model-name HuggingFaceTB/SmolLM2-360M-Instruct --reward-embedding-model NeuML/pubmedbert-base-embeddings-8M --n-steps 400 --per_device_train_batch_size 1 --gradient_accumulation_steps 8 --seed $RANDOM --embed
# # # # Oracle reward
# accelerate launch --num_processes 8 --config_file config/deepspeed_zero3.yaml src/nll_to_po/medical/grpo_llm.py --model-name HuggingFaceTB/SmolLM2-360M-Instruct --reward-embedding-model NeuML/pubmedbert-base-embeddings-8M --n-steps 400 --per_device_train_batch_size 1 --gradient_accumulation_steps 8 --seed $RANDOM --no-embed
# accelerate launch --num_processes 8 --config_file config/deepspeed_zero3.yaml src/nll_to_po/medical/grpo_llm.py --model-name HuggingFaceTB/SmolLM2-360M-Instruct --reward-embedding-model NeuML/pubmedbert-base-embeddings-8M --n-steps 400 --per_device_train_batch_size 1 --gradient_accumulation_steps 8 --seed $RANDOM --no-embed
# accelerate launch --num_processes 8 --config_file config/deepspeed_zero3.yaml src/nll_to_po/medical/grpo_llm.py --model-name HuggingFaceTB/SmolLM2-360M-Instruct --reward-embedding-model NeuML/pubmedbert-base-embeddings-8M --n-steps 400 --per_device_train_batch_size 1 --gradient_accumulation_steps 8 --seed $RANDOM --no-embed
# # # # SFT
# accelerate launch --num_processes 8 --config_file config/deepspeed_zero3.yaml src/nll_to_po/medical/sft_llm.py --model-name HuggingFaceTB/SmolLM2-360M-Instruct  --max-steps 400 --per_device_train_batch_size 1 --gradient_accumulation_steps 8 --seed $RANDOM
# accelerate launch --num_processes 8 --config_file config/deepspeed_zero3.yaml src/nll_to_po/medical/sft_llm.py --model-name HuggingFaceTB/SmolLM2-360M-Instruct  --max-steps 400 --per_device_train_batch_size 1 --gradient_accumulation_steps 8 --seed $RANDOM
# accelerate launch --num_processes 8 --config_file config/deepspeed_zero3.yaml src/nll_to_po/medical/sft_llm.py --model-name HuggingFaceTB/SmolLM2-360M-Instruct  --max-steps 400 --per_device_train_batch_size 1 --gradient_accumulation_steps 8 --seed $RANDOM
# # # embed U_he trace
accelerate launch --num_processes 8 --config_file config/deepspeed_zero3.yaml src/nll_to_po/medical/grpo_llm.py --model-name HuggingFaceTB/SmolLM2-360M-Instruct --reward-embedding-model NeuML/pubmedbert-base-embeddings-8M --n-steps 400 --per_device_train_batch_size 1 --gradient_accumulation_steps 8 --seed $RANDOM --embed --u_star_type "trace"
accelerate launch --num_processes 8 --config_file config/deepspeed_zero3.yaml src/nll_to_po/medical/grpo_llm.py --model-name HuggingFaceTB/SmolLM2-360M-Instruct --reward-embedding-model NeuML/pubmedbert-base-embeddings-8M --n-steps 400 --per_device_train_batch_size 1 --gradient_accumulation_steps 8 --seed $RANDOM --embed --u_star_type "trace"
accelerate launch --num_processes 8 --config_file config/deepspeed_zero3.yaml src/nll_to_po/medical/grpo_llm.py --model-name HuggingFaceTB/SmolLM2-360M-Instruct --reward-embedding-model NeuML/pubmedbert-base-embeddings-8M --n-steps 400 --per_device_train_batch_size 1 --gradient_accumulation_steps 8 --seed $RANDOM --embed --u_star_type "trace"
# # # embed U_he cov
accelerate launch --num_processes 8 --config_file config/deepspeed_zero3.yaml src/nll_to_po/medical/grpo_llm.py --model-name HuggingFaceTB/SmolLM2-360M-Instruct --reward-embedding-model NeuML/pubmedbert-base-embeddings-8M --n-steps 400 --per_device_train_batch_size 1 --gradient_accumulation_steps 8 --seed $RANDOM --embed --u_star_type "cov"
accelerate launch --num_processes 8 --config_file config/deepspeed_zero3.yaml src/nll_to_po/medical/grpo_llm.py --model-name HuggingFaceTB/SmolLM2-360M-Instruct --reward-embedding-model NeuML/pubmedbert-base-embeddings-8M --n-steps 400 --per_device_train_batch_size 1 --gradient_accumulation_steps 8 --seed $RANDOM --embed --u_star_type "cov"
accelerate launch --num_processes 8 --config_file config/deepspeed_zero3.yaml src/nll_to_po/medical/grpo_llm.py --model-name HuggingFaceTB/SmolLM2-360M-Instruct --reward-embedding-model NeuML/pubmedbert-base-embeddings-8M --n-steps 400 --per_device_train_batch_size 1 --gradient_accumulation_steps 8 --seed $RANDOM --embed --u_star_type "cov"



# # SmolLM2-136M